title: Zihang Wang's Homepage
page-top-title: Zihang Wang 
top-section-bg-text: Be what you wanna be
home-subtitle: Myname&ensp;|&ensp;Zihang Wang 
copyright-text: '&copy; Zihang Wang 2026. All Rights Reserved.'
